<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit018fb9d0059cbfede6ddf0adab221e92
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Spatie\\SchemaOrg\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Spatie\\SchemaOrg\\' => 
        array (
            0 => __DIR__ . '/..' . '/spatie/schema-org/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit018fb9d0059cbfede6ddf0adab221e92::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit018fb9d0059cbfede6ddf0adab221e92::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
